### ISSUE TITLE
Pinterest error

### ISSUE THREAD

**Issue by Buliwyfa** [GreenMeteor/humhub-oauth#4]
### What steps will reproduce the problem?
Click on login using Pinterest
pinterest screen to allow

click on OK and error
![3](https://user-images.githubusercontent.com/13509685/35529141-70462f3c-0530-11e8-98c7-92cda8250bc8.png)

### What is the expected result?
login to humhub

### What do you get instead?
An error
```
Exception – yii\authclient\InvalidResponseException
Request failed with code: 301, message: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="https://api.pinterest.com/v1/me/?access_token=AYGpWLY83EvmXcU16flWs2UcSo8uFQ5dQU8bLEVEqfy-H2BAdAAAAAA">https://api.pinterest.com/v1/me/?access_token=AYGpWLY83EvmXcU16flWs2UcSo8uFQ5dQU8bLEVEqfy-H2BAdAAAAAA</a>. If not click the link.

```

### Additional info

Also, Icon on login using Pinterest missing

| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 7
| Operating system  windsows|

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
I'm still working on refactoring a few of the oauths, but thanks for the information! :smile:

**Comment by Felli** [comment]
Also to note, we use Font Awesome 5 for all our oauths now as it's updated more often and supports more brands than 4 and older.

**Comment by Felli** [comment]
Could you change this line to `return $this->api('v1/me', 'GET');` and see if that fixes the issue?

https://github.com/GreenMeteor/humhub-oauth/blob/master/oauth/Pinterest/Pinterest.php#L52

**Comment by Buliwyfa** [comment]
Try it and I get this error
![2018-02-02_124827](https://user-images.githubusercontent.com/13509685/35731827-781c24a2-0817-11e8-9ac7-43aa0cc2d693.png)

**Comment by Felli** [comment]
This is because Pinterest doesn't access connection over HTTP, but over HTTPS, but I'll continue working on the oauth for the issues that I've ran into.

**Comment by Buliwyfa** [comment]
but test site has only https and all URL set on Pinterest are https


![qqqqq](https://user-images.githubusercontent.com/13509685/35760573-672eb91a-0881-11e8-8053-4606676a4651.png)

**Comment by Felli** [comment]
I've fixed this error now I've gotten a new one. :laughing: 

```
yii\authclient\InvalidResponseException: Request failed with code: 404, message: { "message": "404: Not Found", "type": "http" }
```

**Comment by Felli** [comment]
I'll talk with some of the other members of Green Meteor to find a fix for this, I'm also going to get into contact with Pinterest about this to see what can be done to fix this.

**Comment by Felli** [comment]
@Buliwyfa I've gotten good and bad news from the Pinterest devs;

### Good
They will be looking into this issue and getting back to me if it's an issue on their end.

### Bad
They're having issues with their approval system and are going to work on fixing this before looking into this issue.

So hopefully we'll get things working for me to submit this as well as a few other new Oauths into v1.3 brand of HumHub. :+1:
