### ISSUE TITLE
instagram

### ISSUE THREAD

**Issue by Buliwyfa** [GreenMeteor/humhub-oauth#6]
### What steps will reproduce the problem?
When login using Instagram I get the error

     "Missing E-Mail Attribute from AuthClient."

On Instagram 
https://www.instagram.com/developer/authorization/

The Application is live and reviewed

### What is the expected result?
Be logged in on humhub

### What do you get instead?

     "Missing E-Mail Attribute from AuthClient."

### Additional info
| Q                | A
| ---------------- | ---
| HumHub version   | 1.2.4
| PHP version      | 7.0
| Operating system | linux

> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

**Comment by Felli** [comment]
Once my server is up again I'll do some tests.

**Comment by Felli** [comment]
Hmm... Just tested this... The error only happens for those that sign in with an email that is already in use, once I connect from `/user/account/connected-accounts` the message does not display for me anymore... Might be something to look into later. :thinking: Please try the same and see if this fixes the issue (I know it's a crappy way of going around it, but this is more of a HumHub & Yii issue at this time...).

**Comment by Buliwyfa** [comment]
I try it with a just created Instagram account making sure email was not on humhub and I get the same...
Could it be something else?

**Comment by Felli** [comment]
I'll look into this, might just be a frontend issue on the login page.

**Comment by Buliwyfa** [comment]
Maybe I will try to do some debugging tomorrow

**Comment by Buliwyfa** [comment]
it seems email is not sent, this is the var_dump from initUserAttributes() on a brand new Instagram account and email never used on our Humhub instance

array(8) { 
["id"]=> string(10) "7215**53" 
["username"]=> string(15) "s****mark" 
["profile_picture"]=> string(139) "https://scontent-d*******************9_a.jpg" 
["full_name"]=> string(15) "server bookmark" 
["bio"]=> string(0) ""
["website"]=> string(0) ""
 ["is_business"]=> bool(false)
 ["counts"]=> array(3) { ["media"]=> int(0)
 ["follows"]=> int(0)
 ["followed_by"]=> int(0) 
} }

**Comment by Felli** [comment]
Working on a fix as we speak!

**Comment by Buliwyfa** [comment]
great :)

**Comment by Felli** [comment]
Would seem to be an issue on Instagram, as they don't support for a call to email that I've found... 
 Might have to drop support for Instagram if I can't find a workaround for the frontend issue... :thinking:

**Comment by Buliwyfa** [comment]
Same thing here, no way to get the email...

Also I found this;
https://stackoverflow.com/questions/26503975/can-i-get-user-email-using-instagram-api-login

**Comment by Felli** [comment]
The @GreenMeteor/core-members are now putting it up for discussion on whether or not to depreciate the Instagram oauth or not.

**Comment by ArchBlood** [comment]
I'm in favor of dropping support temporarily till the issue can be resolved or fixed within Instagram's platform.

**Comment by Felli** [comment]
I would recommend no longer using this oauth, and for those that have been using it, have all users unconnect accounts and then remove the oauth from your site. (Keeping open for future reference!)

**Comment by Felli** [comment]
Has now officially been deprecated in HumHub v1.3 so I'm going to go ahead and close this issue. :smile:
